create or replace TABLE k_database_name.k_schema_name.k_project_name_APPLICATION_DTLS (
	APPLICATION_ID NUMBER(38,0) autoincrement start 1 increment 1 order,
	APPLICATION_NAME VARCHAR(200),
	APPLICATION_DESC VARCHAR(200),
	IS_ACTIVE VARCHAR(4),
	CREATED_DATE DATE,
	CREATED_BY VARCHAR(200),
	LAST_MODIFIED_DATE DATE,
	LAST_MODIFIED_BY VARCHAR(200)
);