create or replace TABLE COMETL_CONTROL_TEST_DB.COMETL_CONTROL_EMEA.PA_APPLICATION_DTLS (
	APPLICATION_ID NUMBER(38,0) autoincrement start 1 increment 1 order,
	APPLICATION_NAME VARCHAR(200),
	APPLICATION_DESC VARCHAR(200),
	IS_ACTIVE VARCHAR(4),
	CREATED_DATE DATE,
	CREATED_BY VARCHAR(200),
	LAST_MODIFIED_DATE DATE,
	LAST_MODIFIED_BY VARCHAR(200)
);