create or replace TABLE COMETL_CONTROL_TEST_DB.COMETL_CONTROL_EMEA.PA_BATCH_RUN_DTLS (
	BATCH_ID NUMBER(38,0),
	APPLICATION_ID NUMBER(38,0),
	SUBJECT_AREA_NAME VARCHAR(200),
	EXECUTION_DATE DATE,
	LOAD_START_TIME TIMESTAMP_NTZ(9),
	LOAD_END_TIME TIMESTAMP_NTZ(9),
	LOAD_TIME_TAKEN_SECS NUMBER(38,0),
	LOAD_STATUS VARCHAR(200)
);