create or replace TABLE k_database_name.k_schema_name.k_project_name_BATCH_RUN_DTLS (
	BATCH_ID NUMBER(38,0),
	APPLICATION_ID NUMBER(38,0),
	SUBJECT_AREA_NAME VARCHAR(200),
	EXECUTION_DATE DATE,
	LOAD_START_TIME TIMESTAMP_NTZ(9),
	LOAD_END_TIME TIMESTAMP_NTZ(9),
	LOAD_TIME_TAKEN_SECS NUMBER(38,0),
	LOAD_STATUS VARCHAR(200)
);