create or replace TABLE k_database_name.k_schema_name.k_project_name_AUDIT_DTLS (
	AUDIT_ID NUMBER(38,0),
	APPLICATION_ID NUMBER(38,0),
	BATCH_ID NUMBER(38,0),
	SUBJECT_AREA_NAME VARCHAR(200),
	INTERFACE_NAME VARCHAR(200),
	TASK_NAME VARCHAR(200),
	TASK_TYPE VARCHAR(200),
	EXECUTION_START_TIME TIMESTAMP_NTZ(9),
	EXECUTION_END_TIME TIMESTAMP_NTZ(9),
	EXECUTION_TIME_SECS NUMBER(38,0),
	EXECUTION_STATUS VARCHAR(4),
	EXECUTION_STATUS_DESC VARCHAR(200),
	ERROR_DESC VARCHAR(16777216),
	CREATED_DATE TIMESTAMP_NTZ(9),
	CREATED_BY VARCHAR(200),
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9),
	LAST_UPDATE_BY VARCHAR(200)
);



create or replace TABLE k_database_name.k_schema_name.k_project_name_AUDIT_EXEC_DTLS (
	AUDIT_ID NUMBER(38,0),
	APPLICATION_ID NUMBER(38,0),
	BATCH_ID NUMBER(38,0),
	REF_ID VARCHAR(200),
	SUB_PROCESS_NM VARCHAR(200),
	PROCESS_TYPE VARCHAR(200),
	EXECUTION_START_TIME TIMESTAMP_NTZ(9),
	EXECUTION_END_TIME TIMESTAMP_NTZ(9),
	EXECUTION_TIME_SECS NUMBER(38,0),
	EXECUTION_STATUS VARCHAR(4),
	EXECUTION_STATUS_DESC VARCHAR(200),
	SRC_RECORD_COUNT NUMBER(38,0),
	TGT_RECORD_COUNT NUMBER(38,0),
	DIFF_RECORD_COUNT NUMBER(38,0),
	ERROR_DESC VARCHAR(16777216),
	CREATED_DATE TIMESTAMP_NTZ(9),
	CREATED_BY VARCHAR(200),
	LAST_UPDATE_DATE TIMESTAMP_NTZ(9),
	LAST_UPDATE_BY VARCHAR(200)
);


create or replace TABLE k_database_name.k_schema_name.k_project_name_BATCH_RUN_DTLS (
	BATCH_ID NUMBER(38,0),
	APPLICATION_ID NUMBER(38,0),
	SUBJECT_AREA_NAME VARCHAR(200),
	EXECUTION_DATE DATE,
	LOAD_START_TIME TIMESTAMP_NTZ(9),
	LOAD_END_TIME TIMESTAMP_NTZ(9),
	LOAD_TIME_TAKEN_SECS NUMBER(38,0),
	LOAD_STATUS VARCHAR(200)
);