--liquibase formatted sql

--changeset elangr02:jira05

USE DATABASE COMETL_PA_AMER_TEST_DB;

USE SCHEMA COMETL_PA_INT_STG;


create or replace TABLE PA_LND_IDENTIFIED_HCP_ADDR_FULL (
	PFZ_CUST_ID NUMBER(18,0),
	PFZ_ADDR_ID NUMBER(38,0),
	ADDR_1 VARCHAR(300),
	ADDR_2 VARCHAR(300),
	ADDR_3 VARCHAR(300),
	CITY VARCHAR(300),
	ST VARCHAR(6),
	ZIP5 VARCHAR(20),
	ZIP4 VARCHAR(20),
	CNTY VARCHAR(100),
	CNTRY VARCHAR(100),
	BEST_CALL_ADDR_IND VARCHAR(1),
	ADDR_TYPE_CD VARCHAR(20)
);


create or replace TABLE PA_LND_LOV_ZIP (
	ZIP5 VARCHAR(20),
	CITY VARCHAR(300),
	ST VARCHAR(2),
	ZIP_OCCURRENCE NUMBER(18,0),
	STATE_COUNT_3ZIP NUMBER(30,0),
	ZIP_ADDR_COUNT NUMBER(30,0),
	CITY_ADDR_COUNT NUMBER(18,0)
);


create or replace TABLE PA_LND_HCOS (
	PFZ_CUST_ID NUMBER(18,0),
	IMS_HCOS_ID VARCHAR(100),
	FULL_NM VARCHAR(128) COLLATE 'en-ci',
	CUST_SUB_TYPE_1_CD VARCHAR(20) COLLATE 'en-ci',
	HCOS_COT_ID VARCHAR(20) COLLATE 'en-ci',
	PFZ_ADDR_ID NUMBER(38,0),
	ADDR_1 VARCHAR(300),
	ADDR_2 VARCHAR(300),
	ADDR_3 VARCHAR(300),
	CITY VARCHAR(300),
	ST VARCHAR(6),
	ZIP5 VARCHAR(20),
	CNTRY VARCHAR(100)
);


create or replace TABLE PA_LND_IDENTIFIED_HCP_FULL (
	PFZ_CUST_ID NUMBER(18,0),
	IMS_NUMBER VARCHAR(20) COLLATE 'en-ci',
	ME_NUM VARCHAR(20) COLLATE 'en-ci',
	PRES_LNAME VARCHAR(100) COLLATE 'en-ci',
	PRES_FNAME VARCHAR(100) COLLATE 'en-ci',
	PRES_MIDL_NM VARCHAR(100) COLLATE 'en-ci',
	IMS_SPEC_CD VARCHAR(20) COLLATE 'en-ci',
	PRES_TITL_CD VARCHAR(20) COLLATE 'en-ci',
	CUST_SUB_TYPE_1_CD VARCHAR(20) COLLATE 'en-ci',
	SFA NUMBER(1,0),
	RX NUMBER(1,0),
	CALLS NUMBER(1,0),
	FULL_ALIGN NUMBER(1,0)
);


create or replace TABLE PA_LND_UNIDENTIFIED_HCP (
	PFZ_CUST_ID NUMBER(18,0),
	IMS_NUMBER VARCHAR(16777216),
	PRES_LNAME VARCHAR(100) COLLATE 'en-ci',
	IMS_SPEC_CD VARCHAR(20) COLLATE 'en-ci',
	CUST_SUB_TYPE_1_CD VARCHAR(20) COLLATE 'en-ci',
	PRES_PROF_TYPE_ID VARCHAR(2) COLLATE 'en-ci',
	PRES_PROF_TYPE_DESC VARCHAR(50) COLLATE 'en-ci',
	PFZ_ADDR_ID NUMBER(38,0),
	ADDR_1 VARCHAR(300),
	ADDR_2 VARCHAR(300),
	ADDR_3 VARCHAR(300),
	CITY VARCHAR(300),
	ST VARCHAR(6),
	ZIP5 VARCHAR(20),
	CNTRY VARCHAR(100)
);


create or replace TABLE PA_LND_DDD (
	PFZ_CUST_ID NUMBER(18,0),
	IMS_DDD_ID VARCHAR(100),
	FULL_NM VARCHAR(128) COLLATE 'en-ci',
	CUST_SUB_TYPE_1_CD VARCHAR(20) COLLATE 'en-ci',
	SUB_CAT_CD VARCHAR(20) COLLATE 'en-ci',
	PFZ_ADDR_ID NUMBER(38,0),
	ADDR_1 VARCHAR(300),
	ADDR_2 VARCHAR(300),
	ADDR_3 VARCHAR(300),
	CITY VARCHAR(300),
	ST VARCHAR(6),
	ZIP5 VARCHAR(20),
	CNTRY VARCHAR(100)
);


create or replace TABLE PA_LND_LOV_HCOS_COT_CODE (
	HCOS_COT_ID VARCHAR(15),
	HCOS_COT_DESC VARCHAR(133),
	COT_CLSFN_ID VARCHAR(15),
	COT_CLSFN VARCHAR(50),
	COT_FCLT_TYPE_ID VARCHAR(15),
	COT_FCLT_TYPE VARCHAR(50),
	COT_SPEC_ID VARCHAR(15),
	COT_SPEC VARCHAR(50)
);


create or replace TABLE PA_LND_MCO (
	PFZ_CUST_ID NUMBER(18,0),
	MCO_ID VARCHAR(100),
	SRC_SYS VARCHAR(50),
	KEY_TYPE VARCHAR(14),
	LINK_TO_REFERENCE_ACCOUNT VARCHAR(100),
	FULL_NM VARCHAR(128) COLLATE 'en-ci',
	CUST_SUB_TYPE_1_CD VARCHAR(20) COLLATE 'en-ci',
	CUST_SUB_TYPE_2_CD VARCHAR(20) COLLATE 'en-ci',
	PFZ_ADDR_ID NUMBER(38,0),
	ADDR_1 VARCHAR(300),
	ADDR_2 VARCHAR(300),
	ADDR_3 VARCHAR(300),
	CITY VARCHAR(300),
	ST VARCHAR(6),
	ZIP5 VARCHAR(20),
	CNTRY VARCHAR(100)
);


create or replace TABLE PA_LND_XREF_CUST_TO_SOURCE (
	SRC_CUST_ID VARCHAR(100) COLLATE 'en-ci',
	SRC_SYS VARCHAR(50),
	PFZ_CUST_ID NUMBER(18,0),
	KEY_TYPE VARCHAR(14),
	EFF_DT DATE,
	END_DT DATE
);

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_ADDR_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_ADDR_REL_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_EXTNL_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_SUBTYP_SEQ START WITH 1 INCREMENT BY 1;

create or replace TABLE PA_STG_CUST (
	BATCH_ID VARCHAR(10),
	UNIQUE_ROW_ID NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_SEQ.NEXTVAL,
	ACTION VARCHAR(4),
	CUST_ID VARCHAR(20) NOT NULL,
	CUST_NM VARCHAR(100) NOT NULL,
	CUST_MID_NM VARCHAR(100),
	CUST_FIRST_NM VARCHAR(100),
	CUST_GRP_CD VARCHAR(20) NOT NULL,
	CUST_TYP_CD VARCHAR(20) NOT NULL,
	DYN_ALGN_IND VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CORP_TK NUMBER(38,0) NOT NULL,
	SPAN_TK NUMBER(38,0) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	ERROR_FLAG VARCHAR(1),
	constraint XAK1PA_CUST unique (CUST_ID, SPAN_TK)
);

create or replace TABLE PA_STG_CUST_SUBTYP (
	BATCH_ID VARCHAR(10),
	UNIQUE_ROW_ID NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_SUBTYP_SEQ.NEXTVAL,
	ACTION VARCHAR(4),
	CUST_ID NUMBER(38,0) NOT NULL,
	CUST_SUBTYP_TYP_CD VARCHAR(20) NOT NULL,
	CUST_SUBTYP_CD VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	ERROR_FLAG VARCHAR(1),
	constraint XAK1PA_CUST_SUBTYP unique (CUST_ID, CUST_SUBTYP_TYP_CD, CUST_SUBTYP_CD, EFF_DT)
);

create or replace TABLE PA_STG_CUST_ADDR_REL (
	BATCH_ID VARCHAR(10),
	UNIQUE_ROW_ID NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_ADDR_REL_SEQ.NEXTVAL,
	ACTION VARCHAR(5),
	CUST_ID NUMBER(38,0) NOT NULL,
	CUST_ADDR_ID VARCHAR(20) NOT NULL,
	CUST_ADDR_REL_TYP_CD VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	ERROR_FLAG VARCHAR(1)
);

create or replace TABLE PA_STG_CUST_ADDR (
	BATCH_ID VARCHAR(10),
	UNIQUE_ROW_ID NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_ADDR_SEQ.NEXTVAL,
	ACTION VARCHAR(10),
	CUST_ADDR_ID VARCHAR(20) NOT NULL,
	SPAN_TK NUMBER(38,0),
	ADDR_LN_1 VARCHAR(100) NOT NULL,
	ADDR_LN_2 VARCHAR(100),
	CITY_NM VARCHAR(100),
	STATE_CD VARCHAR(20),
	POSTAL_ID VARCHAR(20),
	ALGN_GEO01_ID VARCHAR(20),
	ALGN_GEO02_ID VARCHAR(20),
	ALGN_GEO03_ID VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	ERROR_FLAG VARCHAR(1)
);

create or replace TABLE PA_STG_CUST_EXTNL (
	BATCH_ID VARCHAR(10),
	UNIQUE_ROW_ID NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT_STG.PA_STG_CUST_EXTNL_SEQ.NEXTVAL,
	ACTION VARCHAR(10),
	CUST_ID NUMBER(38,0) NOT NULL,
	CUST_EXTNL_TYP_CD VARCHAR(20) NOT NULL,
	CUST_EXTNL_VAL VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	ERROR_FLAG VARCHAR(1),
	constraint XAK1PA_CUST_EXTNL unique (CUST_ID, CUST_EXTNL_TYP_CD, EFF_DT)
);
