--liquibase formatted sql

--changeset elangr02:jira08

USE DATABASE COMETL_PA_AMER_TEST_DB;

USE SCHEMA COMETL_PA_INT;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_REL_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SUBTYP_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE SEQUENCE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_EXTNL_SEQ START WITH 1 INCREMENT BY 1;


create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST (
	CUST_TK NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SEQ.NEXTVAL,
	CUST_ID VARCHAR(20) NOT NULL,
	CUST_NM VARCHAR(100) NOT NULL,
	CUST_MID_NM VARCHAR(100),
	CUST_FIRST_NM VARCHAR(100),
	CORP_TK NUMBER(38,0) NOT NULL,
	SPAN_TK NUMBER(38,0) NOT NULL,
	CUST_GRP_CD VARCHAR(20) NOT NULL,
	CUST_TYP_CD VARCHAR(20) NOT NULL,
	DYN_ALGN_IND VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	constraint XAK1PA_CUST unique (CUST_ID, SPAN_TK),
	constraint XPKPA_CUST primary key (CUST_TK)
);


create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SUBTYP (
	CUST_SUBTYP_TK NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SUBTYP_SEQ.NEXTVAL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_SUBTYP_TYP_CD VARCHAR(20) NOT NULL,
	CUST_SUBTYP_CD VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	constraint XAK1PA_CUST_SUBTYP unique (CUST_TK, CUST_SUBTYP_TYP_CD, CUST_SUBTYP_CD, EFF_DT),
	constraint XPKPA_CUST_SUBTYP primary key (CUST_SUBTYP_TK)
);

create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_REL (
	CUST_ADDR_REL_TK NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_REL_SEQ.NEXTVAL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_ADDR_TK NUMBER(38,0) NOT NULL,
	CUST_ADDR_REL_TYP_CD VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);

create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR (
	CUST_ADDR_TK NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_SEQ.NEXTVAL,
	SPAN_TK NUMBER(38,0) NOT NULL,
	CUST_ADDR_ID VARCHAR(20) NOT NULL,
	ADDR_LN_1 VARCHAR(100) NOT NULL,
	ADDR_LN_2 VARCHAR(100),
	CITY_NM VARCHAR(100),
	STATE_CD VARCHAR(20),
	POSTAL_ID VARCHAR(20),
	ALGN_GEO01_ID VARCHAR(20),
	ALGN_GEO02_ID VARCHAR(20),
	ALGN_GEO03_ID VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);


create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_EXTNL (
	CUST_EXTNL_TK NUMBER(38,0) NOT NULL DEFAULT COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_EXTNL_SEQ.NEXTVAL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_EXTNL_TYP_CD VARCHAR(20) NOT NULL,
	CUST_EXTNL_VAL VARCHAR(20) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	constraint XAK1PA_CUST_EXTNL unique (CUST_TK, CUST_EXTNL_TYP_CD, EFF_DT),
	constraint XPKPA_CUST_EXTNL primary key (CUST_EXTNL_TK)
);






CREATE OR REPLACE STREAM COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_STREAM ON TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST;

CREATE OR REPLACE STREAM COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_STREAM ON TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR;

CREATE OR REPLACE STREAM COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_REL_STREAM ON TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_ADDR_REL;

CREATE OR REPLACE STREAM COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SUBTYP_STREAM ON TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_SUBTYP;

CREATE OR REPLACE STREAM COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_EXTNL_STREAM ON TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PA_CUST_EXTNL;





create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PAA_CUST (
	AUD_CD VARCHAR(1) NOT NULL,
	ALIGN_AUD_CD VARCHAR(1) NOT NULL,
	AUD_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_END_DT TIMESTAMP_NTZ(9),
	AUD_USER VARCHAR(20) NOT NULL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_ID VARCHAR(20) NOT NULL,
	CUST_NM VARCHAR(100) NOT NULL,
	CUST_FIRST_NM VARCHAR(100),
	CORP_TK NUMBER(38,0) NOT NULL,
	SPAN_TK NUMBER(38,0) NOT NULL,
	CUST_GRP_CD VARCHAR(20) NOT NULL,
	CUST_TYP_CD VARCHAR(20) NOT NULL,
	DYN_ALGN_IND VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);

create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PAA_CUST_ADDR (
	AUD_CD VARCHAR(1) NOT NULL,
	ALIGN_AUD_CD VARCHAR(1) NOT NULL,
	AUD_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_END_DT TIMESTAMP_NTZ(9),
	AUD_USER VARCHAR(20) NOT NULL,
	CUST_ADDR_TK NUMBER(38,0) NOT NULL,
	SPAN_TK NUMBER(38,0) NOT NULL,
	CUST_ADDR_ID VARCHAR(20) NOT NULL,
	ADDR_LN_1 VARCHAR(100) NOT NULL,
	ADDR_LN_2 VARCHAR(100),
	CITY_NM VARCHAR(100),
	STATE_CD VARCHAR(20),
	POSTAL_ID VARCHAR(20),
	ALGN_GEO01_ID VARCHAR(20),
	ALGN_GEO02_ID VARCHAR(20),
	ALGN_GEO03_ID VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);


create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PAA_CUST_ADDR_REL (
	AUD_CD VARCHAR(1) NOT NULL,
	ALIGN_AUD_CD VARCHAR(1) NOT NULL,
	AUD_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_END_DT TIMESTAMP_NTZ(9),
	AUD_USER VARCHAR(20) NOT NULL,
	CUST_ADDR_REL_TK NUMBER(38,0) NOT NULL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_ADDR_TK NUMBER(38,0) NOT NULL,
	CUST_ADDR_REL_TYP_CD VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);

create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PAA_CUST_EXTNL (
	AUD_CD VARCHAR(1) NOT NULL,
	ALIGN_AUD_CD VARCHAR(1) NOT NULL,
	AUD_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_END_DT TIMESTAMP_NTZ(9),
	AUD_USER VARCHAR(20) NOT NULL,
	CUST_EXTNL_TK NUMBER(38,0) NOT NULL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_EXTNL_TYP_CD VARCHAR(20) NOT NULL,
	CUST_EXTNL_VAL VARCHAR(20) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL
);


create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PAA_CUST_SUBTYP (
	AUD_CD VARCHAR(1) NOT NULL,
	ALIGN_AUD_CD VARCHAR(1) NOT NULL,
	AUD_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_END_DT TIMESTAMP_NTZ(9),
	AUD_USER VARCHAR(20) NOT NULL,
	CUST_SUBTYP_TK NUMBER(38,0) NOT NULL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_SUBTYP_TYP_CD VARCHAR(20) NOT NULL,
	CUST_SUBTYP_CD VARCHAR(20) NOT NULL,
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);