-- liquibase formatted sql
-- changeset elangr02:jira10

USE DATABASE COMETL_PA_AMER_TEST_DB;

USE SCHEMA COMETL_PA_INT_STG;

create or replace TABLE COMETL_PA_AMER_TEST_DB.COMETL_PA_INT.PAA_CUST (
	AUD_CD VARCHAR(1) NOT NULL,
	ALIGN_AUD_CD VARCHAR(1) NOT NULL,
	AUD_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	OLD_END_DT TIMESTAMP_NTZ(9),
	AUD_USER VARCHAR(20) NOT NULL,
	CUST_TK NUMBER(38,0) NOT NULL,
	CUST_ID VARCHAR(20) NOT NULL,
	CUST_NM VARCHAR(100) NOT NULL,
	CUST_MID_NM VARCHAR(100),
	CUST_FIRST_NM VARCHAR(100),
	CORP_TK NUMBER(38,0) NOT NULL,
	SPAN_TK NUMBER(38,0) NOT NULL,
	CUST_GRP_CD VARCHAR(20) NOT NULL,
	CUST_TYP_CD VARCHAR(20) NOT NULL,
	DYN_ALGN_IND VARCHAR(20),
	EFF_DT TIMESTAMP_NTZ(9) NOT NULL,
	END_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_DT TIMESTAMP_NTZ(9) NOT NULL,
	CRE_USER_TK NUMBER(38,0) NOT NULL,
	UPD_DT TIMESTAMP_NTZ(9) NOT NULL,
	UPD_USER_TK NUMBER(38,0) NOT NULL
);