-- liquibase formatted sql
-- changeset elangr02:jira11

USE DATABASE COMETL_PA_AMER_TEST_DB;
USE SCHEMA COMETL_PA_INT_STG;
ALTER TABLE "COMETL_PA_AMER_TEST_DB"."COMETL_PA_INT_STG"."PA_TAB_XREF" RENAME TO 
"COMETL_PA_AMER_TEST_DB"."COMETL_PA_INT_STG"."PA_PG_LOAD_STATUS";