name: Common Component Maker

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the new branch. It should start with "feature" and not be "main".'
        required: true
      oldString:
        description: 'Old string to replace'
        required: true
      newString:
        description: 'New string to replace with'
        required: true

jobs:
  create_and_replace:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format and existence
        run: |
          if [[ "${{ github.event.inputs.branchName }}" == "main" ]]; then
            echo "Branch name cannot be 'main', please provide a different name."
            exit 1
          elif [[ ! "${{ github.event.inputs.branchName }}" =~ ^feature.* ]]; then
            echo "Branch name should start with 'feature', please provide a different name."
            exit 1
          # elif git show-ref --verify --quiet "refs/heads/${{ github.event.inputs.branchName }}"; then
          #   echo "Branch already exists, exiting."
          #   exit 1
          fi

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Check if branch exists
        id: check_branch
        run: |
          git fetch --all
          if git rev-parse --verify --quiet refs/remotes/origin/${{ github.event.inputs.branchName }}; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create branch if it doesn't exist
        if: steps.check_branch.outputs.branch_exists == 'false'
        run: |
          git checkout -b ${{ github.event.inputs.branchName }}
          git push origin ${{ github.event.inputs.branchName }}

      - name: Pull latest changes if branch exists
        if: steps.check_branch.outputs.branch_exists == 'true'
        run: |
          git checkout ${{ github.event.inputs.branchName }}
          git pull origin ${{ github.event.inputs.branchName }}

      - name: Perform string replacement
        run: |
          find . -type f -name "*" -exec sed -i "s/${{ github.event.inputs.oldString }}/${{ github.event.inputs.newString }}/g" {} +

      - name: Push changes to new branch
        run: |
          git push origin ${{ github.event.inputs.branchName }}
