name: Common Component Maker

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the new branch. It should start with "feature" and not be "main".'
        required: true
      oldString:
        description: 'Old string to replace'
        required: true
      newString:
        description: 'New string to replace with'
        required: true

jobs:
  create_and_replace:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format
        run: |
          if [[ "${{ github.event.inputs.branchName }}" == "main" ]]; then
            echo "Branch name cannot be 'main', please provide a different name."
            exit 1
          elif [[ ! "${{ github.event.inputs.branchName }}" =~ ^feature.* ]]; then
            echo "Branch name should start with 'feature', please provide a different name."
            exit 1
          fi

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Check if branch already exists
        run: |
          if git branch --list ${{ github.event.inputs.branchName }}; then
            echo "Branch already exists, exiting."
            exit 1
          fi

      - name: Create new branch
        run: git checkout -b ${{ github.event.inputs.branchName }}

      - name: Perform string replacement
        run: |
          find . -type f -exec sed -i "s/${{ github.event.inputs.oldString }}/${{ github.event.inputs.newString }}/g" {} +

      - name: Push changes to new branch
        run: |
          git push origin ${{ github.event.inputs.branchName }}
