name: Common Components Maker

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the new branch'
        required: true
      oldString:
        description: 'Old string to replace'
        required: true
      newString:
        description: 'New string to replace with'
        required: true

jobs:
  create_and_replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Check if branch already exists
        run: |
          if git show-ref --verify --quiet "refs/heads/${{ github.event.inputs.branchName }}"; then
            echo "Branch already exists, exiting."
            exit 1
          fi

      - name: Create new branch
        run: git checkout -b ${{ github.event.inputs.branchName }}

      - name: Perform string replacement
        run: |
          find . -type f -exec sed -i "s/${{ github.event.inputs.oldString }}/${{ github.event.inputs.newString }}/g" {} +

      - name: Push changes to new branch
        run: |
          git push origin ${{ github.event.inputs.branchName }}
